apiVersion: v1
kind: Service
metadata:
  name: kubernetes-service
  labels:
    app: guestbook-app
spec:
  type: LoadBalancer
  selector:
    app: kubernetes-pod
  ports:
    - port: 80
      targetPort: 80